RX-74 joined
Restream/reindexer-java pull request #26
Opened 2021-01-14 09:05 UTC by ryazanovvv

2021-01-15 13:51 UTC, evgeniycheban requested changes
Оставил несколько комментариев.

2021-01-15 13:51 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CJsonItemWriter.java
> +                .filter(field -> field.getAnnotation(Reindex.class) != null)
`isAnnotationPresent`

2021-01-15 13:51 UTC, evgeniycheban commented on src/test/java/ru/rt/restream/reindexer/connector/JoinTest.java
> +        List<Actor> mainActor = result.getJoinResult("mainActor");
Не хватает проверок.

2021-01-18 17:41 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/annotations/Joined.java
> + *
Удалил пока joined

2021-01-18 17:41 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/annotations/ReindexAnnotationScanner.java
> +                        .filter(f -> f.getAnnotation(Reindex.class).name().equals(joinIndex))
Удалено вместо с  Joined

2021-01-18 17:41 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/binding/cproto/cjson/CJsonItemWriter.java
> +                .filter(field -> field.getAnnotation(Reindex.class) != null)
Удалено вместо с Joined

2021-01-18 17:42 UTC, ryazanovvv commented on src/test/java/ru/rt/restream/reindexer/connector/JoinTest.java
> +        List<Actor> mainActor = result.getJoinResult("mainActor");
Удалил, добавил новые тесты

2021-01-20 11:43 UTC, evgeniycheban approved these changes

2021-01-20 12:01 UTC, merged