RX-74 sql log query
Restream/reindexer-java pull request #36
Opened 2021-01-27 18:30 UTC by ryazanovvv

2021-01-28 13:58 UTC, evgeniycheban requested changes
Оставил комментарии.

2021-01-28 13:58 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +        logBuilder.join(joinQuery.logBuilder, field, joinType);
Думаю тут нужна проверка `LOGGER.isDebugEnabled`, чтобы не собирать запрос если не установлен уровень логгирования `debug`.

2021-01-29 07:48 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java
> +        public String field;
Поправил

2021-01-29 07:48 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java
> +        public boolean isJsonObject;
Поправил

2021-01-29 07:48 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java
> +        switch (condition) {
Добавил

2021-01-29 07:48 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/QueryLogBuilder.java
> +        switch (type) {
Добавил

2021-01-29 07:49 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +        logBuilder.join(joinQuery.logBuilder, field, joinType);
Здесь запрос не собирается. Тут только добавляется инфа о джойне в билдер. Вся сборка происходит в методе getSql().

2021-01-29 12:35 UTC, evgeniycheban approved these changes

2021-01-29 14:41 UTC, merged