RX-74 Rename Configuration class
Restream/reindexer-java pull request #39
Opened 2021-02-05 09:08 UTC by steleal

WINKDEV-8610: Переименовать Configuration в ReindexerConfiguration

2021-02-05 09:26 UTC, ryazanovvv approved these changes

2021-02-05 17:13 UTC, evgeniycheban requested changes

2021-02-05 17:13 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/ReindexerConfiguration.java
> +public final class ReindexerConfiguration {
Поправь название еще в readme плз.

2021-02-06 08:41 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/ReindexerConfiguration.java
> +public final class ReindexerConfiguration {
Сделал, спасибо.

2021-02-06 13:49 UTC, evgeniycheban approved these changes

2021-02-06 13:50 UTC, merged