Feature/rx 74 accelerate cproto tests
Restream/reindexer-java pull request #40
Opened 2021-02-15 05:45 UTC by steleal

These changes accelerate all of the tests. 
On my computer full time of execution before refactoring was about **8 minutes.**
After refactoring it was became about **40 sec**. 
Tests became 12 times faster, cproto tests - 15 times faster, and builtin tests - 2.5 times.

2021-02-18 10:49 UTC, evgeniycheban requested changes

2021-02-18 10:49 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +            binding.dropNamespace(n.getName());
Реиндексер поддерживает удаление данных из неймспейса без удаления самого неймспейса.  
Предлагаю добавить метод `void truncateNamespace(String namespaceName)` в `Binding`, для `cproto` это команда `19`, для `builtin` это метод `reindexer_truncate_namespace` в C++.

2021-02-19 07:44 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +            binding.dropNamespace(n.getName());
метод `void truncateNamespace(String namespaceName)` в Binding добавил.
Но при использовании его в clear() появились ошибки в тестах. Похоже,  что, в отличие от dropNamespace этот метод не сбрасывает счетчик и существующие индексы (их количество). Т.е. если мы добавили 100 записей, сделали truncate, и добавили еще одну запись, то ее id = 101, а не 1. 

Порядковый номер сгенеренного id проверяется здесь 
```
BuiltinReindexerTest>ReindexerTest.testTransactionInsertMultithreadingWithCommit:1209 
BuiltinReindexerTest>ReindexerTest.testTransactionUpsertWithSerialId:1637 
BuiltinReindexerTest>ReindexerTest.testUpsertWithSerialId:1615 
(а еще в 1694, 2035, но там не падает)
JsonTest.testSelect:109 » IllegalState Exactly one item expected, but there is...
JsonTest.testUpdateField:135 » IllegalState Exactly one item expected, but the...
```

Количество индексов здесь:
`CprotoReindexerTest.testOpenNamespace:58 `

Предлагаю оставить реализацию clear на вызовах dropNamespace(), не на truncateNamespace().

2021-02-19 08:36 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +            binding.dropNamespace(n.getName());
Володя Гаранин предложил каждому тесту свой уникальный namespace, генерить автоматически.

2021-02-19 10:00 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +            binding.dropNamespace(n.getName());
Мне кажется, что имеет смысл сначала WINKDEV-8882(возвращать уже открытый namespace) сделать, потом clear на truncateNamespace переделать, иначе все равно при попытке повторно использовать namespace будет падать.

2021-02-19 13:55 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +            binding.dropNamespace(n.getName());
Сделал namespaceMap и конструктор в Reindexer как protected, отнаследовал от него ClearDbReindexer в тестовый package, вынес clear() в него, и поправил DbLocator.

2021-02-20 20:46 UTC, evgeniycheban requested changes

2021-02-20 20:46 UTC, evgeniycheban commented on src/test/java/ru/rt/restream/reindexer/db/DbLocator.java
> +        ClearDbReindexer db = instancesForUse.getOrDefault(type, null);
`getOrDefault(type, null)` тоже самое что `get(type)`.

2021-02-20 20:46 UTC, evgeniycheban commented on src/test/java/ru/rt/restream/reindexer/db/DbBaseTest.java
> +    protected abstract void initDb();
Думаю будет лучше реализовать этот метод тут и сделать абстрактный метод возвращающий `DbLocator.Type`, например:
```
@BeforeAll
void initDb() {
  db = DbLocator.getDb(getDbType());
}

protected abstract DbLocator.Type getDbType();
```
Из плюсов не нужно будет использовать аннотацию `@BeforeAll` в наследниках.

2021-02-21 06:35 UTC, steleal commented on src/test/java/ru/rt/restream/reindexer/db/DbLocator.java
> +        ClearDbReindexer db = instancesForUse.getOrDefault(type, null);
Точно, спасибо!

2021-02-21 06:37 UTC, steleal commented on src/test/java/ru/rt/restream/reindexer/db/DbBaseTest.java
> +    protected abstract void initDb();
Спасибо, оценил, так очевиднее.
Сделал.

2021-02-21 21:09 UTC, evgeniycheban approved these changes

2021-02-21 21:09 UTC, merged