WIP: RX-74 add supporting of JSON into insert/update/upsert
Restream/reindexer-java pull request #44
Opened 2021-03-11 07:23 UTC by steleal

2021-03-17 06:11 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +    public <T> void insert(String namespaceName, byte[] json, Class<T> itemClass) {
1) Вместо byte[] json лучше использовать String.
2) itemClass тут не нужен - неймспейс из мапы можно получить по строке
3) <T> здесь не нужен

По другим новым методам тоже самое

2021-03-17 06:20 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +    public JsonIterator executeToJson() {
Тут прям много дублирующегося кода. Может вынести общую часть в отдельный метод? См. гошный коннектор: bindings.go:249

2021-03-17 06:22 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/JsonIterator.java
> +        return new String(result.getBytes());
Лучше использовать другой конструктор - return new String(bytes, StandardCharsets.UTF_8);

2021-03-17 06:25 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +    public <T> void insert(String namespaceName, byte[] json, Class<T> itemClass) {
1. Содрал с Гошки. Ок, сделаю стринг.
2. Согласен, писал до rebase от мастер.
3. ???

2021-03-17 06:26 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +    public JsonIterator executeToJson() {
Спасибо, сделаю.

2021-03-17 06:26 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/JsonIterator.java
> +        return new String(result.getBytes());
Ок

2021-03-17 06:31 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +    public <T> void insert(String namespaceName, byte[] json, Class<T> itemClass) {
Поправил коммент

2021-03-17 07:24 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +    public <T> void insert(String namespaceName, byte[] json, Class<T> itemClass) {
Сделал, спасибо!

2021-03-17 07:24 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +    public JsonIterator executeToJson() {
Сделал, спасибо!

2021-03-17 07:24 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/JsonIterator.java
> +        return new String(result.getBytes());
Сделал, спасибо!

2021-03-18 14:53 UTC, evgeniycheban requested changes
Оставил несколько комментариев ниже.

2021-03-18 14:53 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/JsonIterator.java
> +                .append("{ \"")
Пробелы лишние лучше убрать.

2021-03-18 14:53 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/JsonIterator.java
> +            builder.append(next()).append(',');
Тут будет лишняя запятая в конце.

2021-03-18 14:53 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +    public void insert(String namespaceName, String json) {
Аналогичные методы нужно так же добавить в объекты `Namespace` и `Transaction`.

2021-03-19 05:23 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/JsonIterator.java
> +                .append("{ \"")
Убрал, спасибо

2021-03-19 05:23 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/JsonIterator.java
> +            builder.append(next()).append(',');
Убрал. Спасибо!

2021-03-19 12:16 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/Reindexer.java
> +    public void insert(String namespaceName, String json) {
Готово, спасибо!

2021-03-19 13:40 UTC, evgeniycheban approved these changes

2021-03-22 09:06 UTC, merged