RX-74 maven info added to README.md
Restream/reindexer-java pull request #48
Opened 2021-03-15 12:51 UTC by ryazanovvv

2021-03-15 20:54 UTC, evgeniycheban requested changes

2021-03-15 20:54 UTC, evgeniycheban commented on README.md
> +                .where("id", EQ, 5)
Форматирование лучше оставить как было.

2021-03-16 06:50 UTC, ryazanovvv commented on README.md
> +                .where("id", EQ, 5)
Поправил

2021-03-16 16:34 UTC, evgeniycheban approved these changes

2021-03-17 06:05 UTC, merged