Feature/Winkdev-9426 refactoring of modifyJsonItem
Restream/reindexer-java pull request #51
Opened 2021-03-22 13:27 UTC by steleal

2021-03-23 10:19 UTC, evgeniycheban requested changes

2021-03-23 10:19 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/binding/cproto/json/JsonItemSerializer.java
> +public class JsonItemSerializer<T> implements ItemSerializer<T> {
Лучше тут вместо `T` сделать `String` и кастить уже в `ItemSerializerFactory`.

2021-03-23 12:41 UTC, evgeniycheban approved these changes

2021-03-24 12:12 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/binding/cproto/ItemSerializer.java
> +    static <T> ItemSerializer<T> getInstance(Class<?> itemClass, PayloadType payloadType) {
Class<T> itemClass?

2021-03-24 13:59 UTC, merged