RX-74 javadocs added
Restream/reindexer-java pull request #52
Opened 2021-03-29 11:31 UTC by ryazanovvv

2021-03-30 13:05 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/util/JsonSerializer.java
> +     * Convert object to json-formatted string.
Предлагаю "Convert**s** **an** object to json-formatted string."

2021-03-30 13:09 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/util/package-info.java
> + * Contains utility classes that that are "shared" by other packages
that that - опечатка или так задумано?
И точка.

2021-03-30 13:10 UTC, steleal commented on src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
> +import ru.rt.restream.reindexer.*;
Import wildcard ?

2021-03-30 13:11 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/ReindexerResponse.java
> +     * Create new instance.
Предлагаю Creates new instance.

2021-03-31 07:38 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/IndexType.java
> +     * Fast select by EQ and SET match. Used by default. Allows slow and ineffecient sorting by field
Поправил

2021-03-31 07:38 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/IndexType.java
> +     * Available only DWITHIN match. Acceptable only for [2]double field type
Поправил

2021-03-31 07:38 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/IndexType.java
> +     * Column index. Can't perform fast select because it's implemented with full-scan technic.
Поправил

2021-03-31 07:38 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +import java.util.*;
Поправил

2021-03-31 07:38 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +import static ru.rt.restream.reindexer.QueryLogBuilder.AggregateType.*;
Поправил

2021-03-31 07:38 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/exceptions/ReindexerExceptionFactory.java
> + * Provides method for constructing various reindexer exceptions.
Поправил

2021-03-31 07:38 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/util/JsonSerializer.java
> +     * Convert object to json-formatted string.
Поправил

2021-03-31 07:40 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/util/package-info.java
> + * Contains utility classes that that are "shared" by other packages
Поправил

2021-03-31 07:40 UTC, ryazanovvv commented on src/test/java/ru/rt/restream/reindexer/connector/ReindexerTest.java
> +import ru.rt.restream.reindexer.*;
Поправил

2021-03-31 07:40 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/ReindexerResponse.java
> +     * Create new instance.
Поправил

2021-04-01 15:56 UTC, evgeniycheban requested changes
Оставил несколько комментариев.
Нужно проверить, что во всех javadoc комментариях есть теги `@param` и `@return` там где необходимо.

2021-04-01 15:56 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/AggregationResult.java
> +         * Get the current facet values.
Тут и дальше не хватает `@return`.

2021-04-01 15:56 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/Query.java
> + * A Query builder. Objects of this class provides methods for creating a query to DB object.
`An instance of this class provides methods for building a query for database objects.`
Можно так.

2021-04-01 15:56 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +         */
Тут и далее `@return the {@link AggregationFacetRequest} for further customizations`

2021-04-01 15:56 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/annotations/package-info.java
> +package ru.rt.restream.reindexer.annotations;
Добавь пожалуйста в новых файлах в конце новую строку.

2021-04-02 08:25 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/AggregationResult.java
> +         * Get the current facet values.
добавил

2021-04-02 08:25 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/Query.java
> +         */
Поправил

2021-04-02 08:26 UTC, ryazanovvv commented on src/main/java/ru/rt/restream/reindexer/annotations/package-info.java
> +package ru.rt.restream.reindexer.annotations;
Добавил

2021-04-02 09:42 UTC, steleal approved these changes

2021-04-02 12:43 UTC, evgeniycheban approved these changes

2021-04-02 13:13 UTC, merged