Add FullTextConfig - options of full text search for index with type "TEXT".
Restream/reindexer-java pull request #72
Opened 2021-10-18 10:34 UTC by steleal

2021-10-19 10:13 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/ReindexerIndex.java
> +        this.fullTextConfig = (indexType == IndexType.TEXT) ? fullTextConfig : null;
Думаю тут лучше будет бросить исключение, т.к это явно ошибка конфигурации пользователя.

2021-10-20 05:45 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/ReindexerIndex.java
> +        this.fullTextConfig = (indexType == IndexType.TEXT) ? fullTextConfig : null;
Спасибо, добавил   IllegalArgumentException()

2021-10-20 08:36 UTC, steleal commented on src/main/java/ru/rt/restream/reindexer/annotations/FullText.java
> +    boolean enableTranslit() default true;
Точно, спасибо, исправил!

2021-10-20 13:04 UTC, evgeniycheban requested changes

2021-10-20 13:04 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/ReindexerIndex.java
> +        if (indexType == IndexType.TEXT || fullTextConfig == null) {
Давай сделаем тут 2 проверки:
1. Проверяем, что `fullTextConfig != null`, кидаем исключение.
2. Проверяем, что `indexType == IndexType.TEXT`, кидаем исключение.

2021-10-20 13:04 UTC, evgeniycheban commented on src/main/java/ru/rt/restream/reindexer/annotations/FullText.java
> +     * Enable wrong keyboard layout variants processing. e.g. term "keynbr" will match word "лунтик".
Не хватает `@return` в javadoc.

2021-10-21 00:33 UTC, evgeniycheban approved these changes

2021-10-21 00:34 UTC, merged